openapi: "3.0.0"
info:
  version: 1.0.0
  title: My API
servers:
  - url: http://localhost:3001/first-micros
paths:
  /healthcheck:
    get:
      summary: Healthcheck of API
      tags: ["healthcheck"]
      responses:
        "200":
          description: success
        "500":
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      required:
        - message
      properties:
        message:
          type: string
